### ISSUE TITLE
Facing problem with SNOPT Library while inputing make -j command

### ISSUE THREAD

**Issue by Cramer54** [RobotLocomotion/gcs-science-robotics#10]
I downloaded the SNOPT Library and did licence activation yet I am facing the following issues :- 

/home/anik/drake/tools/install/libdrake/BUILD.bazel:58:25: in cc_whole_archive_library rule //tools/install/libdrake:libdrake_components_whole_archive: 
Traceback (most recent call last):
	File "/home/anik/drake/third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl", line 38, column 38, in _cc_whole_archive_library_impl
		cc_toolchain = _find_cc_toolchain(ctx)
	File "/home/anik/drake/third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl", line 25, column 13, in _find_cc_toolchain
		fail("In order to use find_cc_toolchain, your rule has to depend on C++ toolchain. See find_cc_toolchain.bzl docs for details.")  # noqa
Error in fail: In order to use find_cc_toolchain, your rule has to depend on C++ toolchain. See find_cc_toolchain.bzl docs for details.

**Comment by RussTedrake** [comment]
I would need to know more about your platform to help. It seems that it can't find the compiler.

FWIW -- We now have mature implementations of the algorithms from this paper in Drake master, including a number of improvements.  I have reproductions for most of the examples in my [manipulation repo](https://manipulation.mit.edu/trajectories.html#gcs). Depending on your goals, you might be able to simply `pip install manipulation` or run directly from deepnote.

**Comment by Cramer54** [comment]
I was trying local installation using the code you provided. While giving the command make -j , an error showed that it was not accessing the SNOPT files. Hence, I downloaded it from the UCSD website, and after that, I gave the path link to the workspace. After that, it is also unable to find the compiler. I am sharing what I added to the workspace;

new_local_repository(
    name = "snopt",
    path = "/home/anik/SNOPT",
    build_file_content = """
cc_library(
    name = "snopt_cwrap",
    srcs = glob(["lib/*.c", "lib/*.cpp"]),
    hdrs = glob(["include/*.h"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
)
""",
)

I am new to this SNOPT Library and Drake Framework. Is this way correct ?

**Comment by RussTedrake** [comment]
This isn't the right place to get help about building Drake. Consider stackoverflow, where more people involved with the build system can help: https://drake.mit.edu/getting_help.html .  But in order to get a response there, you'll definitely need to provide more details about your setup.
